import Head from "next/head";
import {BsFillMoonStarsFill} from 'react-icons/bs';
import { AiFillLinkedin } from 'react-icons/ai';
import { FaGithubAlt } from 'react-icons/fa';
import { HiMail } from 'react-icons/hi';
import { useState } from "react";
import Image from 'next/image';
import main from '../public/main-image.jpg';
import code from '../public/code.png';
import design from '../public/design.png';
import consulting from '../public/consulting.png';
import web1 from '../public/web1.jpg';
// import apple from '../public/Apple-ai.jpg';
import web2 from '../public/web2.png';
// import cdi from '../public/CDI-ai.jpeg';
import web3 from '../public/web3.png';
// import tindog from '../public/tindog-ai.jpeg';
import web4 from '../public/web4.png';
// import dice from '../public/Dice-ai-image.jpeg';
import web5 from '../public/web5.png';
// import drumkit from '../public/drumkit-ai-image.jpeg';
import web6 from '../public/web6.png';
// import simon from '../public/simon-ai.jpeg';



export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
           <Head>
  
        <title>Zamzam Ali | Software Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" style={{ borderRadius:'50%' }} />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className=" min-h-screen">
    <nav className="py-10 mb-12 flex flex-col items-center md:flex-row md:justify-between dark:text-white">
          <h1 className="text-xl font-burtons mb-2 md:mb-0">MyPortfolio</h1>
        <div className="flex flex-col items-center md:flex-row">
            <BsFillMoonStarsFill
              onClick={() => setDarkMode(!darkMode)}
              className={`cursor-pointer text-2xl ${darkMode ? 'text-white' : 'text-gray-800'}`}
            />
            <a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md md:ml-8 mt-2 md:mt-0" href="/CS-Resume.pdf">
              View Resume
            </a>
        </div>
    </nav>

          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl dark:teal-400">Hi! I&rsquo;m Zamzam Ali</h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">Product Specialist</h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 md:text-xl max-w-lg mx-auto">I leverage data and software to make everything one click away, even cooking! Just kidding, that passion project is still in the ideation phase.</p>
            <p className="text-md pb-5 leading-8 text-gray-800 dark:text-gray-200 md:text-xl max-w-lg mx-auto">Welcome to my world!</p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            <a href="https://www.linkedin.com/in/zamzam-ali/">
              <AiFillLinkedin />
            </a>
            <a href="https://github.com/developer020">
              <FaGithubAlt />
            </a>
            <a href="mailto:zeemohamudali@gmail.com">
              <HiMail />
            </a>
          </div>
          <div className="relative mx-auto w-80 h-80 mt-20">
            <Image alt="image" className="rounded-full w-80 h-80 mt-20 md:h-96 md:w-96" src={main} layout="fill" objectFit="cover" />
          </div>
        </section>

        {/* SECTION 2 */}
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Expertise</h3>
            {/*<p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            Where software solutions meets business problems.</p> 
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200"> The nurtured skills that I anchor in all my projects include technical prowess in development, and business acumen in the form of <span className=" py-4 text-teal-600">Research and Analysis</span>, <span className=" py-4 text-teal-600">Technical Documentation</span>, <span className=" py-4 text-teal-600">Relationship Management</span> <span className=" py-4 text-teal-600">Management</span>, and <span className=" py-4 text-teal-600"></span>.
            </p>*/}
          </div>
          <div className="lg:flex items-center justify-center gap-10">
            <div className=" text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image alt="image" src={design} />
              <h3 className="text-lg font-medium pt-8 pb-2">Software</h3>
              {/* <p className="py-2">Unlock the potential of your online presence with my visually stunning and user-friendly designs, tailored to elevate your website&rsquo;s impact and engage your audience effortlessly.</p> */}
              <h4 className="py-4 text-teal-600">Problem Solving</h4>
              <h4 className="py-4 text-teal-600">Documentation</h4>
              <h4 className="py-4 text-teal-600">Version Control</h4>
              <h4 className="py-4 text-teal-600">Testing/QA (Quality Assurance)</h4>  
            </div>
            <div className=" text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
            <Image alt="image" src={code} />
              <h3 className="text-lg font-medium pt-8 pb-2">Data</h3>
              {/* <p className="py-2">I orchestrate an ensemble of precision instruments, carefully chosen to maintain unwavering organization, foster seamless collaboration within teams, and meticulously record every pulse of code that breathes life into your digital masterpiece.</p> */}
              <h4 className="py-4 text-teal-600">Research and Analysis</h4>
              <h4 className="py-4 text-teal-600">Data Visualization</h4>
              <h4 className="py-4 text-teal-600">Statistical Modeling</h4>
              <h4 className="py-4 text-teal-600">Data Cleaning and Preprocessing</h4>
            </div>
            <div className=" text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image alt="image" src={consulting} />
              <h3 className="text-lg font-medium pt-8 pb-2">Business</h3>
              {/* <p className="py-2">My commitment to delivering an impeccable user experience is underpinned by servers that align with cutting-edge frameworks and tools that ensure flawless integration and fluid transitions, all within a robust ecosystem of viewport and device support systems.</p> */}
              <h4 className="py-4 text-teal-600">Product Quality Monitoring</h4>
              <h4 className="py-4 text-teal-600">Growth Analysis</h4>
              <h4 className="py-4 text-teal-600">Relationship Management</h4>
              <h4 className="py-4 text-teal-600">Cross-Functional Collaboration</h4>
            </div>
          </div>
        </section>
        
        {/* SECTION 3 */}
        <section className="py-10">
          <div>
            <div>
              <h3 className="text-4xl py-1 text-teal-600 font-medium md:text-4xl dark:teal-400">RESUME</h3>
              <p className="text-md py-2 leading-8text-gray-800 dark:text-gray-200">
                In case you missed it at the top of the page, here&rsquo;s my resume!
              </p>
            </div>
           {/* <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            <span className="text-teal-600">Personal projects</span> and <span className="text-teal-600">digital products</span> I&rsquo;ve created for companies.
            </p>*/}
          </div>
          <div className=" items-center justify-center h-screen flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
              <div className="w-full max-w-sm relative basis-1/3 flex-1">
                  <a href="/CS-Resume.pdf">
                      <Image 
                        alt="image"
                        src={web1} 
                        className="rounded-lg object-cover" 
                        width={"100%"} 
                        height={"100%"} 
                        layout="responsive"
                      />
                        <div className="rounded-lg absolute inset-0 flex items-center justify-center bg-black bg-opacity-75 opacity-0 hover:opacity-100 transition duration-300">
                          <p className="text-white text-lg font-semibold absolute">
                            career brag sheet
                          </p>
                        </div>
                    </a>
                </div>
               {/*<div className="relative basis-1/3 flex-1">
                <a href="https://lanesapharma.com/">
                    <Image
                      alt="image"
                      className="rounded-lg object-cover"
                      width={"100%"}
                      height={"100%"}
                      layout="responsive"
                      src={web2}
                    />
                        <div className="rounded-lg absolute inset-0 flex items-center justify-center bg-black bg-opacity-75 opacity-0 hover:opacity-100 transition duration-300">
                          <p className="text-white text-lg font-semibold absolute">
                            Lanesa Pharma
                          </p>
                        </div>
                  </a>
              </div>
              <div className="relative basis-1/3 flex-1">
                  <a href="https://mountain-slopes-international-website.vercel.app/">
                    <Image
                      alt="image"
                      className="rounded-lg object-cover"
                      width={"100%"}
                      height={"100%"}
                      layout="responsive"
                      src={web3}
                    />
                        <div className="rounded-lg absolute inset-0 flex items-center justify-center bg-black bg-opacity-75 opacity-0 hover:opacity-100 transition duration-300">
                          <p className="text-white text-lg font-semibold absolute">
                            Mountain Slopes Intl.
                          </p>
                        </div>
                  </a>
              </div>
              <div className="relative basis-1/3 flex-1">
                <a href="https://developer020.github.io/TinDog/">
                  <Image
                    alt="image"
                    className="rounded-lg object-cover"
                    width={"100%"}
                    height={"100%"}
                    layout="responsive"
                    src={web4}
                  />
                      <div className="rounded-lg absolute inset-0 flex items-center justify-center bg-black bg-opacity-75 opacity-0 hover:opacity-100 transition duration-300">
                        <p className="text-white text-lg font-semibold absolute">
                          Tindog(Tinder for dogs)
                        </p>
                      </div>
                </a>
              </div>
              <div className="relative basis-1/3 flex-1">
                <a href="https://developer020.github.io/Dice-Game/">
                  <Image
                    alt="image"
                    className="rounded-lg object-cover"
                    width={"100%"}
                    height={"100%"}
                    layout="responsive"
                    src={web5}
                  />
                      <div className="rounded-lg absolute inset-0 flex items-center justify-center bg-black bg-opacity-75 opacity-0 hover:opacity-100 transition duration-300">
                        <p className="text-white text-lg font-semibold absolute">
                          Dice
                        </p>
                      </div>
                </a>
              </div>
              <div className="relative basis-1/3 flex-1">
                <a href="https://developer020.github.io/Drum-Kit/">
                  <Image
                    alt="image"
                    className="rounded-lg object-cover"
                    width={"100%"}
                    height={"100%"}
                    layout="responsive"
                    src={web6}
                  />
                      <div className="rounded-lg absolute inset-0 flex items-center justify-center bg-black bg-opacity-75 opacity-0 hover:opacity-100 transition duration-300">
                        <p className="text-white text-lg font-semibold absolute">
                          Drum-Kit
                        </p>
                      </div>
                </a>
              </div>*/}
          </div>
        </section>
      </main>
    </div>
  );
}
