import Head from "next/head";
import {BsFillMoonStarsFill} from 'react-icons/bs';
import { AiFillLinkedin } from 'react-icons/ai';
import { FaGithubAlt } from 'react-icons/fa';
import { HiMail } from 'react-icons/hi';
import { useState } from "react";
import Image from 'next/image';
import main from '../public/main-image.jpeg';
import code from '../public/code.png';
import design from '../public/design.png';
import consulting from '../public/consulting.png';
import web1 from '../public/web1.png';
// import apple from '../public/Apple-ai.jpg';
import web2 from '../public/web2.png';
// import cdi from '../public/CDI-ai.jpeg';
import web3 from '../public/web3.png';
// import tindog from '../public/tindog-ai.jpeg';
import web4 from '../public/web4.png';
// import dice from '../public/Dice-ai-image.jpeg';
import web5 from '../public/web5.png';
// import drumkit from '../public/drumkit-ai-image.jpeg';
import web6 from '../public/web6.png';
// import simon from '../public/simon-ai.jpeg';



export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
           <Head>
        <title>Zamzam Ali Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className=" min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark: text-white">
            <h1 className="text-xl font-burtons">MyPortfolio</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)}   className={`cursor-pointer text-2xl ${darkMode ? 'text-white' : 'text-gray-800'}`}
/>
                </li>
              <li>
                <a className="bg-gradient-to-r from-cyan-500 to-teal-500 tex-white px-4 py-2 rounded-md ml-8" href="#">View Resume</a>
                </li>
            </ul>
          </nav>

          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl dark:teal-400">Zamzam Ali</h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">Frontend Developer</h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 md:text-xl max-w-lg mx-auto">Software Engineer, currently specializing in frontend. I have a well rounded understanding of Computer Science and a passion for innovation. Welcome to my world! Lets create something special.</p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            <a href="https://www.linkedin.com/in/zamzam-ali/">
              <AiFillLinkedin />
            </a>
            <a href="https://github.com/developer020">
              <FaGithubAlt />
            </a>
            <a href="mailto:zeemohamudali@gmail.com">
              <HiMail />
            </a>
          </div>
          <div className="relative mx-auto w-80 h-80 mt-20">
            <Image alt="image" className="rounded-full w-80 h-80 mt-20 md:h-96 md:w-96" src={main} layout="fill" objectFit="cover" />
          </div>
        </section>

        {/* SECTION 2 */}
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            Are you ready to turn your digital dreams into vibrant realities? With my pixel-perfect precision and sprinkle of coding magic, I bring your wildest design visions to life. From dazzling animations that dance across the screen to seamless interactions that leave users spellbound. Whether you need a website that pops like a <span className=" text-teal-500">confetti explosion</span> or an interface that glows like a <span className=" text-teal-500">neon rave</span>, I've got you covered. So, let's embark on an electrifying journey together, where imagination meets innovation and your website becomes the <span className=" text-teal-500">technicolor supernova</span> of the digital universe!
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className=" text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image alt="image" src={design} />
              <h3 className="text-lg font-medium pt-8 pb-2">Design</h3>
              <p className="py-2">Unlock the potential of your online presence with my visually stunning and user-friendly designs, tailored to elevate your website's impact and engage your audience effortlessly.</p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Canva</p>
              <p className="text-gray-800 py-1">Adobe XD</p>
            </div>
            <div className=" text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
            <Image alt="image" src={code} />
              <h3 className="text-lg font-medium pt-8 pb-2">Functionality</h3>
              <p className="py-2">Unlock the potential of your online presence with my visually stunning and user-friendly designs, tailored to elevate your website's impact and engage your audience effortlessly.</p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Canva</p>
              <p className="text-gray-800 py-1">Adobe XD</p>
            </div>
            <div className=" text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image alt="image" src={consulting} />
              <h3 className="text-lg font-medium pt-8 pb-2">Responsiveness</h3>
              <p className="py-2">Unlock the potential of your online presence with my visually stunning and user-friendly designs, tailored to elevate your website's impact and engage your audience effortlessly.</p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Canva</p>
              <p className="text-gray-800 py-1">Adobe XD</p>
            </div>
          </div>
        </section>
        
        {/* SECTION 3 */}
        <section className="py-10">
          <div>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Portfolio</h3>
            <p className="text-md py-2 leading-8text-gray-800 dark:text-gray-200">
              Welcome to my portfolios section, a visual showcase of my creative endeavors and technical prowess. With a keen focus on staying at the forefront of the rapidly evolving digital landscape, I leverage an array of cutting-edge technologies to create exceptional user experiences.<span className="text-teal-600"> React, Bootstrap, Tailwind CSS, JavaScript ES6, Node.js, Express.js</span> etc.
            </p>
          </div>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            Since the beginning of my journey, I&apos;ve done remote work to create digital products
              for <span className="text-teal-600">business and institutions.</span>
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
          <div className="relative basis-1/3 flex-1">
            <a href="https://developer020.github.io/Apple-Dupe/">
                <Image 
                  alt="image"
                  src={web1} 
                  className="rounded-lg object-cover" 
                  width={"100%"} 
                  height={"100%"} 
                  layout="responsive"
                />
                  <div className="rounded-lg absolute inset-0 flex items-center justify-center bg-black bg-opacity-75 opacity-0 hover:opacity-100 transition duration-300">
                    <p className="text-white text-lg font-semibold absolute">
                      Apple Dupe Website
                    </p>
                  </div>
            </a>
            </div>
            <div className="relative basis-1/3 flex-1">
              <Image
                alt="image"
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
                  <div className="rounded-lg absolute inset-0 flex items-center justify-center bg-black bg-opacity-75 opacity-0 hover:opacity-100 transition duration-300">
                    <p className="text-white text-lg font-semibold absolute">
                      Netflix Dupe Website
                    </p>
                  </div>
            </div>
            <div className="relative basis-1/3 flex-1">
                <a href="https://developer020.github.io/Dice-Game/">
                  <Image
                    alt="image"
                    className="rounded-lg object-cover"
                    width={"100%"}
                    height={"100%"}
                    layout="responsive"
                    src={web3}
                  />
                      <div className="rounded-lg absolute inset-0 flex items-center justify-center bg-black bg-opacity-75 opacity-0 hover:opacity-100 transition duration-300">
                        <p className="text-white text-lg font-semibold absolute">
                          Dice Website
                        </p>
                      </div>
                </a>
            </div>
            <div className="relative basis-1/3 flex-1">
              <a href="https://developer020.github.io/Drum-Kit/">
                <Image
                  alt="image"
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web4}
                />
                    <div className="rounded-lg absolute inset-0 flex items-center justify-center bg-black bg-opacity-75 opacity-0 hover:opacity-100 transition duration-300">
                      <p className="text-white text-lg font-semibold absolute">
                        Drum-Kit Website
                      </p>
                    </div>
              </a>
            </div>
            <div className="relative basis-1/3 flex-1">
              <a href="https://developer020.github.io/TinDog/">
                <Image
                  alt="image"
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web5}
                />
                    <div className="rounded-lg absolute inset-0 flex items-center justify-center bg-black bg-opacity-75 opacity-0 hover:opacity-100 transition duration-300">
                      <p className="text-white text-lg font-semibold absolute">
                        Tindog(Tinder for dogs)
                      </p>
                    </div>
              </a>
            </div>
            <div className="relative basis-1/3 flex-1">
              <a href="https://developer020.github.io/CDA/">
                <Image
                  alt="image"
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web6}
                />
                    <div className="rounded-lg absolute inset-0 flex items-center justify-center bg-black bg-opacity-75 opacity-0 hover:opacity-100 transition duration-300">
                      <p className="text-white text-lg font-semibold absolute">
                        Design-Agency Website
                      </p>
                    </div>
              </a>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
